# Generated by Django 3.2.8 on 2022-06-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_sites',
            name='title',
            field=models.CharField(default='-', max_length=255, null=True, unique=True),
        ),
    ]
