# Generated by Django 3.2.8 on 2022-06-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_working_sites_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_sites',
            name='title',
            field=models.CharField(default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='working_sites',
            name='url',
            field=models.URLField(default='https://sudrf.ru/index.php?id=300&act=go_ms_search&searchtype=ms&var=true&ms_type=ms&court_subj=0', max_length=255, null=True, unique=True),
        ),
    ]
