# Generated by Django 3.2.8 on 2022-06-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220613_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_sites',
            name='adress',
            field=models.TextField(default='-', max_length=255, null=True),
        ),
    ]
